export maps2Data = [
{ slopeprefix: "A", x: 909, y: 4365 },
{ slopeprefix: "B", x: 1818, y: 4215 },
{ slopeprefix: "D", x: 1633, y: 6675 },
{ slopeprefix: "G", x: 2912, y: 8685 },
{ slopeprefix: "H", x: 4242, y: 7470 },
{ slopeprefix: "K", x: 5690, y: 5730 },
{ slopeprefix: "11", x: 1919, y: 2100 },
{ slopeprefix: "12", x: 2357, y: 2490 },
{ slopeprefix: "14", x: 2306, y: 3510 },
{ slopeprefix: "15", x: 2458, y: 4020 },
{ slopeprefix: "16", x: 2256, y: 4530 },
{ slopeprefix: "21", x: 3300, y: 3780 },
{ slopeprefix: "19", x: 3603, y: 2970 },
{ slopeprefix: "24", x: 2862, y: 3750 },
{ slopeprefix: "22", x: 2744, y: 5310 },
{ slopeprefix: "23", x: 3131, y: 5610 },
{ slopeprefix: "26", x: 3384, y: 6120 },
{ slopeprefix: "27", x: 2088, y: 7290 },
{ slopeprefix: "26", x: 4192, y: 4680 },
{ slopeprefix: "32", x: 3215, y: 7050 },
{ slopeprefix: "37", x: 4596, y: 5100 },
{ slopeprefix: "43", x: 5101, y: 4830 },
{ slopeprefix: "44", x: 5556, y: 5010 },
{ slopeprefix: "41", x: 5337, y: 5790 },
{ slopeprefix: "45", x: 6852, y: 3210 },
{ slopeprefix: "46", x: 7475, y: 3780 },
{ slopeprefix: "48", x: 8165, y: 2790 },
{ slopeprefix: "47", x: 8519, y: 3510 },
{ slopeprefix: "31", x: 3636, y: 8040 },
{ slopeprefix: "30A", x: 3603, y: 8580 },
{ slopeprefix: "30B", x: 4024, y: 8760 },
{ slopeprefix: "42", x: 5051, y: 7410 },
{ slopeprefix: "36", x: 4781, y: 6210 },
{ slopeprefix: "34", x: 4377, y: 6060 },
{ slopeprefix: "33", x: 3956, y: 6840 },
{ slopeprefix: "13", x: 2862, y: 2130 }
]

export const mapItemsRawSlatta = [
  {
    prefix: '11',
    name: 'Ølkorken',
    fullName: '11-Ølkorken',
    isOpen: true,
    difficulty: 'black',
    type: 'slope',
  },
  {
    prefix: '12',
    name: 'Steinspretten',
    fullName: '12-Steinspretten',
    isOpen: false,
    difficulty: 'red',
    type: 'slope',
  },
  {
    prefix: '13',
    name: 'MusikkBakken',
    fullName: '13-MusikkBakken',
    isOpen: false,
    difficulty: 'blue',
    type: 'slope',
  },
  {
    prefix: '14',
    name: 'Orreleiken',
    fullName: '14-Orreleiken',
    isOpen: true,
    difficulty: 'red',
    type: 'slope',
  },
  {
    prefix: '15',
    name: 'Tiurspranget',
    fullName: '15-Tiurspranget',
    isOpen: true,
    difficulty: 'red',
    type: 'slope',
  },
  {
    prefix: '16',
    name: 'Fugleleiken',
    fullName: '16-Fugleleiken',
    isOpen: true,
    difficulty: 'blue',
    type: 'slope',
  },
  {
    prefix: '19',
    name: 'Rypestien',
    fullName: '19-Rypestien',
    isOpen: false,
    difficulty: 'blue',
    type: 'slope',
  },
  {
    prefix: '21',
    name: 'Sonjaløypa',
    fullName: '21-Sonjaløypa',
    isOpen: true,
    difficulty: 'blue',
    type: 'slope',
  },
  {
    prefix: '22',
    name: 'Telemarken',
    fullName: '22-Telemarken',
    isOpen: false,
    difficulty: 'red',
    type: 'slope',
  },
  {
    prefix: '23',
    name: 'Olaløypa',
    fullName: '23-Olaløypa',
    isOpen: false,
    difficulty: 'black',
    type: 'slope',
  },
  {
    prefix: '24',
    name: 'Vest Alléen',
    fullName: '24-Vest Alléen',
    isOpen: true,
    difficulty: 'blue',
    type: 'slope',
  },
  {
    prefix: '26',
    name: 'Geiloløypa',
    fullName: '26-Geiloløypa',
    isOpen: true,
    difficulty: 'red',
    type: 'slope',
  },
  {
    prefix: '27',
    name: 'Sentrumsbakken',
    fullName: '27-Sentrumsbakken',
    isOpen: true,
    difficulty: 'green',
    type: 'slope',
  },
  {
    prefix: '30A',
    name: 'Slaattaløypa',
    fullName: '30A-Slaattaløypa',
    isOpen: true,
    difficulty: 'green',
    type: 'slope',
  },
  {
    prefix: '30B',
    name: 'Hakkebakken',
    fullName: '30B-Hakkebakken',
    isOpen: true,
    difficulty: 'green',
    type: 'slope',
  },
  {
    prefix: '31',
    name: 'Slaattajordet',
    fullName: '31-Slaattajordet',
    isOpen: true,
    difficulty: 'green',
    type: 'slope',
  },
  {
    prefix: '32',
    name: 'Slaattasvingen',
    fullName: '32-Slaattasvingen',
    isOpen: false,
    difficulty: 'red',
    type: 'slope',
  },
  {
    prefix: '33',
    name: "S'n",
    fullName: "33-S'n",
    isOpen: false,
    difficulty: 'black',
    type: 'slope',
  },
  {
    prefix: '34',
    name: 'Storekorken',
    fullName: '34-Storekorken',
    isOpen: true,
    difficulty: 'red',
    type: 'slope',
  },
  {
    prefix: '35',
    name: 'Bukkene Bruse',
    fullName: '35-Bukkene Bruse',
    isOpen: true,
    difficulty: 'blue',
    type: 'slope',
  },
  {
    prefix: '36',
    name: 'Anne',
    fullName: '36-Anne-løypa',
    isOpen: true,
    difficulty: 'blue',
    type: 'slope',
  },
  {
    prefix: '37',
    name: 'Hexeløypa',
    fullName: '37-Hexeløypa',
    isOpen: true,
    difficulty: 'red',
    type: 'slope',
  },
  {
    prefix: '41',
    name: 'Arne',
    fullName: '41-Arne-løypa',
    isOpen: true,
    difficulty: 'blue',
    type: 'slope',
  },
  {
    prefix: '42',
    name: 'Sentrumsløypa',
    fullName: '42-Sentrumsløypa',
    isOpen: true,
    difficulty: 'green',
    type: 'slope',
  },
  {
    prefix: '43',
    name: 'Barne',
    fullName: '43-Barne-løypa',
    isOpen: true,
    difficulty: 'green',
    type: 'slope',
  },
  {
    prefix: '44',
    name: 'Trineløypa',
    fullName: '44-Trineløypa',
    isOpen: true,
    difficulty: 'blue',
    type: 'slope',
  },
  {
    prefix: '45',
    name: 'Fjell',
    fullName: '45-Fjell-løypa',
    isOpen: false,
    difficulty: 'green',
    type: 'slope',
  },
  {
    prefix: '46',
    name: 'Fjellrypa',
    fullName: '46-Fjellrypa',
    isOpen: false,
    difficulty: 'green',
    type: 'slope',
  },
  {
    prefix: '47',
    name: 'Havsdalsløypa',
    fullName: '47-Havsdalsløypa',
    isOpen: false,
    difficulty: 'blue',
    type: 'slope',
  },
  {
    prefix: '48',
    name: 'Fjellcrossen',
    fullName: '48-Fjellcrossen',
    isOpen: false,
    difficulty: 'blue',
    type: 'slope',
  },
  {
    prefix: 'A',
    name: 'Halstensgårdheisen',
    fullName: 'A-Halstensgårdheisen',
    isOpen: true,
    type: 'lift',
  },
  {
    prefix: 'B',
    name: 'Fugleleiken',
    fullName: 'B-Fugleleiken',
    isOpen: false,
    type: 'lift',
  },
  {
    prefix: 'D',
    name: 'Geiloheisen ekspress',
    fullName: 'D-Geiloheisen ekspress',
    isOpen: true,
    type: 'lift',
  },
  {
    prefix: 'G',
    name: 'Slaattaheisen',
    fullName: 'G-Slaattaheisen',
    isOpen: true,
    type: 'lift',
  },
  {
    prefix: 'G',
    name: 'Barneheisen',
    fullName: 'G-Barneheisen',
    isOpen: true,
    type: 'lift',
  },
  {
    prefix: 'G',
    name: 'Slaatta skibånd',
    fullName: 'G-Slaatta skibånd',
    isOpen: true,
    type: 'lift',
  },
  {
    prefix: 'H',
    name: 'Korken',
    fullName: 'H-Korken',
    isOpen: true,
    type: 'lift',
  },
  {
    prefix: 'K',
    name: 'Arnetrekket',
    fullName: 'K-Arnetrekket',
    isOpen: true,
    type: 'lift',
  },
  {
    prefix: 'K',
    name: 'Barnetrekket',
    fullName: 'K-Barnetrekket',
    isOpen: true,
    type: 'lift',
  },
  {
    prefix: 'K',
    name: 'Havsdalen skibånd 1',
    fullName: 'K-Havsdalen skibånd 1',
    isOpen: true,
    type: 'lift',
  },
  {
    prefix: 'L',
    name: 'Fjellheisen',
    fullName: 'L-Fjellheisen',
    isOpen: false,
    type: 'lift',
  },
]
export const mapItemsRawVestlia = [
  {
    prefix: '50',
    name: 'Bjødnastigen',
    fullName: '50-Bjødnastigen',
    isOpen: true,
    difficulty: 'green',
    type: 'slope',
  },
  {
    prefix: '51',
    name: 'Bjødnaløypa',
    fullName: '51-Bjødnaløypa',
    isOpen: true,
    difficulty: 'green',
    type: 'slope',
  },
  {
    prefix: '52',
    name: 'Eivaløypa',
    fullName: '52-Eivaløypa',
    isOpen: true,
    difficulty: 'blue',
    type: 'slope',
  },
  {
    prefix: '53',
    name: 'Vestlialøypa',
    fullName: '53-Vestlialøypa',
    isOpen: false,
    difficulty: 'red',
    type: 'slope',
  },
  {
    prefix: '54',
    name: 'Randi',
    fullName: '54-Randi-løypa',
    isOpen: true,
    difficulty: 'red',
    type: 'slope',
  },
  {
    prefix: '55',
    name: 'Geiloparken',
    fullName: '55-Geiloparken',
    isOpen: true,
    difficulty: 'black',
    type: 'slope',
  },
  {
    prefix: '56',
    name: 'Trollklubben',
    fullName: '56-Trollklubben',
    isOpen: true,
    difficulty: 'green',
    type: 'slope',
  },
  {
    prefix: '57',
    name: 'Trollbakken m/park',
    fullName: '57-Trollbakken m/park',
    isOpen: true,
    difficulty: 'green',
    type: 'slope',
  },
  {
    prefix: '58',
    name: 'Hallingen',
    fullName: '58-Hallingen',
    isOpen: false,
    difficulty: 'red',
    type: 'slope',
  },
  {
    prefix: '59',
    name: 'Asle',
    fullName: '59-Asle-løypa',
    isOpen: false,
    difficulty: 'red',
    type: 'slope',
  },
  {
    prefix: '61',
    name: 'Hufseløypa',
    fullName: '61-Hufseløypa',
    isOpen: true,
    difficulty: 'green',
    type: 'slope',
  },
  {
    prefix: '63',
    name: 'Davidløypa',
    fullName: '63-Davidløypa',
    isOpen: true,
    difficulty: 'blue',
    type: 'slope',
  },
  {
    prefix: '64',
    name: 'Guroløypa',
    fullName: '64-Guroløypa',
    isOpen: true,
    difficulty: 'blue',
    type: 'slope',
  },
  {
    prefix: '65',
    name: 'Toneløypa',
    fullName: '65-Toneløypa',
    isOpen: true,
    difficulty: 'blue',
    type: 'slope',
  },
  {
    prefix: '66',
    name: 'Eventyrløypa',
    fullName: '66-Eventyrløypa',
    isOpen: true,
    difficulty: 'red',
    type: 'slope',
  },
  {
    prefix: '68',
    name: 'Kikutløypa',
    fullName: '68-Kikutløypa',
    isOpen: true,
    difficulty: 'green',
    type: 'slope',
  },
  {
    prefix: 'M',
    name: 'Vestliaheisen ekspress',
    fullName: 'M-Vestliaheisen ekspress',
    isOpen: true,
    type: 'lift',
  },
  {
    prefix: 'M',
    name: 'Bjødnaheisen',
    fullName: 'M-Bjødnaheisen',
    isOpen: true,
    type: 'lift',
  },
  {
    prefix: 'M',
    name: 'Trollheisen',
    fullName: 'M-Trollheisen',
    isOpen: true,
    type: 'lift',
  },
  {
    prefix: 'N',
    name: 'Trollklubben',
    fullName: 'N-Trollklubben',
    isOpen: true,
    type: 'lift',
  },
  {
    prefix: 'N',
    name: 'Trollklubben skibånd',
    fullName: 'N-Trollklubben skibånd',
    isOpen: true,
    type: 'lift',
  },
  {
    prefix: 'P',
    name: 'Hufseheisen',
    fullName: 'P-Hufseheisen',
    isOpen: false,
    type: 'lift',
  },
  {
    prefix: 'P',
    name: 'Kikut skibånd',
    fullName: 'P-Kikut skibånd',
    isOpen: true,
    type: 'lift',
  },
  {
    prefix: 'R',
    name: 'Toppheisen',
    fullName: 'R-Toppheisen',
    isOpen: true,
    type: 'lift',
  },
  {
    prefix: 'S',
    name: 'Kikutheisen ekspress',
    fullName: 'S-Kikutheisen ekspress',
    isOpen: true,
    type: 'lift',
  },
]

