import { Coordinate, MapItem, MapSide } from './types.ts';

export const slattaCoordinates: Coordinate[] = [
  { id: "11-Ølkorken", x: 19.50, y: 21.04 },
  { id: "A-Halstensgårdheisen", x: 8.83, y: 43.32 },
  { id: "B-Fugleleiken", x: 18.08, y: 42.13 },
  { id: "D-Geiloheisen ekspress", x: 16.50, y: 66.78 },
  { id: "G-Slaattaheisen", x: 28.75, y: 86.53 },
  { id: "G-Barneheisen", x: 32.75, y: 82.52 },
  { id: "G-Slaatta skibånd", x: 26.92, y: 85.19 },
  { id: "H-Korken", x: 42.25, y: 75.39 },
  { id: "K-Arnetrekket", x: 57.00, y: 57.42 },
  { id: "K-Barnetrekket", x: 49.33, y: 47.03 },
  { id: "K-Havsdalen skibånd 1", x: 59.08, y: 50.89 },
  { id: "L-Fjellheisen", x: 59.33, y: 58.02 },
  { id: "12-Steinspretten", x: 22.17, y: 25.07 },
  { id: "13-MusikkBakken", x: 28.58, y: 21.06 },
  { id: "13-MusikkBakken", x: 17.00, y: 38.00 },
  { id: "14-Orreleiken", x: 21.42, y: 36.35 },
  { id: "15-Tiurspranget", x: 24.58, y: 38.43 },
  { id: "16-Fugleleiken", x: 22.83, y: 44.82 },
  { id: "21-Sonjaløypa", x: 34.75, y: 37.25 },
  { id: "22-Telemarken", x: 25.58, y: 54.03 },
  { id: "23-Olaløypa", x: 32.33, y: 48.53 },
  { id: "24-Vest Alléen", x: 30.25, y: 37.25 },
  { id: "26-Geiloløypa", x: 42.58, y: 46.29 },
  { id: "26-Geiloløypa", x: 30.75, y: 63.68 },
  { id: "27-Sentrumsbakken", x: 23.75, y: 69.32 },
  { id: "30A-Slaattaløypa", x: 38.50, y: 83.28 },
  { id: "30B-Hakkebakken", x: 41.92, y: 84.47 },
  { id: "32-Slaattasvingen", x: 36.17, y: 64.42 },
  { id: "33-S'n", x: 40.17, y: 63.83 },
  { id: "34-Storekorken", x: 44.58, y: 64.57 },
  { id: "35-Bukkene Bruse", x: 51.17, y: 59.22 },
  { id: "36-Anne-løypa", x: 47.33, y: 61.60 },
  { id: "37-Hexeløypa", x: 46.50, y: 52.54 },
  { id: "41-Arne-løypa", x: 45.75, y: 47.34 },
  { id: "42-Sentrumsløypa", x: 54.50, y: 68.28 },
  { id: "43-Barne-løypa", x: 52.00, y: 49.72 },
  { id: "44-Trineløypa", x: 54.25, y: 48.38 },
  { id: "19-Rypestien", x: 38.08, y: 30.86 },
  { id: "45-Fjell-løypa", x: 70.00, y: 27.59 },
  { id: "46-Fjellrypa", x: 77.42, y: 35.91 },
  { id: "47-Havsdalsløypa", x: 87.50, y: 31.31 },
  { id: "48-Fjellcrossen", x: 83.67, y: 24.92 }
]

export const vestliaCoordinates: Coordinate[] = [
  { id: "P-Hufseheisen", x: 2.75, y: 67.20 },
  { id: "P-Kikut skibånd", x: 6.08, y: 67.07 },
  { id: "S-Kikutheisen ekspress", x: 60.67, y: 63.77 },
  { id: "R-Toppheisen", x: 6.50, y: 56.63 },
  { id: "N-Trollklubben", x: 89.75, y: 76.40 },
  { id: "N-Trollklubben skibånd", x: 86.17, y: 80.38 },
  { id: "M-Vestliaheisen ekspress", x: 91.00, y: 70.50 },
  { id: "M-Bjødnaheisen", x: 52.33, y: 24.24 },
  { id: "M-Trollheisen", x: 73.83, y: 61.00 },
  { id: "50-Bjødnastigen", x: 62.67, y: 69.38 },
  { id: "51-Bjødnaløypa", x: 59.42, y: 70.89 },
  { id: "52-Eivaløypa", x: 67.33, y: 68.01 },
  { id: "53-Vestlialøypa", x: 67.17, y: 61.15 },
  { id: "52-Eivaløypa", x: 51.92, y: 45.91 },
  { id: "53-Vestlialøypa", x: 53.42, y: 41.80 },
  { id: "54-Randi-løypa", x: 55.67, y: 37.68 },
  { id: "55-Geiloparken", x: 67.83, y: 54.56 },
  { id: "56-Trollklubben", x: 84.92, y: 76.52 },
  { id: "57-Trollbakken m/park", x: 75.67, y: 65.27 },
  { id: "58-Hallingen", x: 66.83, y: 38.78 },
  { id: "59-Asle-løypa", x: 69.42, y: 37.27 },
  { id: "51-Bjødnaløypa", x: 45.17, y: 23.54 },
  { id: "51-Bjødnaløypa", x: 49.08, y: 48.93 },
  { id: "52-Eivaløypa", x: 47.75, y: 25.05 },
  { id: "61-Hufseløypa", x: 4.92, y: 61.70 },
  { id: "63-Davidløypa", x: 13.42, y: 43.44 },
  { id: "64-Guroløypa", x: 18.25, y: 43.58 },
  { id: "65-Toneløypa", x: 28.00, y: 45.78 },
  { id: "65-Toneløypa", x: 42.25, y: 60.05 },
  { id: "66-Eventyrløypa", x: 45.17, y: 58.27 },
  { id: "68-Kikutløypa", x: 30.58, y: 37.27 }
]

export const mapItemsRawSlatta = [
  {
    prefix: '11',
    name: 'Ølkorken',
    fullName: '11-Ølkorken',
    isOpen: false,
    difficulty: 'black',
    type: 'slope',
  },
  {
    prefix: '12',
    name: 'Steinspretten',
    fullName: '12-Steinspretten',
    isOpen: false,
    difficulty: 'red',
    type: 'slope',
  },
  {
    prefix: '13',
    name: 'MusikkBakken',
    fullName: '13-MusikkBakken',
    isOpen: false,
    difficulty: 'blue',
    type: 'slope',
  },
  {
    prefix: '14',
    name: 'Orreleiken',
    fullName: '14-Orreleiken',
    isOpen: false,
    difficulty: 'red',
    type: 'slope',
  },
  {
    prefix: '15',
    name: 'Tiurspranget',
    fullName: '15-Tiurspranget',
    isOpen: false,
    difficulty: 'red',
    type: 'slope',
  },
  {
    prefix: '16',
    name: 'Fugleleiken',
    fullName: '16-Fugleleiken',
    isOpen: false,
    difficulty: 'blue',
    type: 'slope',
  },
  {
    prefix: '19',
    name: 'Rypestien',
    fullName: '19-Rypestien',
    isOpen: false,
    difficulty: 'blue',
    type: 'slope',
  },
  {
    prefix: '21',
    name: 'Sonjaløypa',
    fullName: '21-Sonjaløypa',
    isOpen: false,
    difficulty: 'blue',
    type: 'slope',
  },
  {
    prefix: '22',
    name: 'Telemarken',
    fullName: '22-Telemarken',
    isOpen: false,
    difficulty: 'red',
    type: 'slope',
  },
  {
    prefix: '23',
    name: 'Olaløypa',
    fullName: '23-Olaløypa',
    isOpen: false,
    difficulty: 'black',
    type: 'slope',
  },
  {
    prefix: '24',
    name: 'Vest Alléen',
    fullName: '24-Vest Alléen',
    isOpen: false,
    difficulty: 'blue',
    type: 'slope',
  },
  {
    prefix: '26',
    name: 'Geiloløypa',
    fullName: '26-Geiloløypa',
    isOpen: false,
    difficulty: 'red',
    type: 'slope',
  },
  {
    prefix: '27',
    name: 'Sentrumsbakken',
    fullName: '27-Sentrumsbakken',
    isOpen: false,
    difficulty: 'green',
    type: 'slope',
  },
  {
    prefix: '30A',
    name: 'Slaattaløypa',
    fullName: '30A-Slaattaløypa',
    isOpen: false,
    difficulty: 'green',
    type: 'slope',
  },
  {
    prefix: '30B',
    name: 'Hakkebakken',
    fullName: '30B-Hakkebakken',
    isOpen: false,
    difficulty: 'green',
    type: 'slope',
  },
  {
    prefix: '31',
    name: 'Slaattajordet',
    fullName: '31-Slaattajordet',
    isOpen: false,
    difficulty: 'green',
    type: 'slope',
  },
  {
    prefix: '32',
    name: 'Slaattasvingen',
    fullName: '32-Slaattasvingen',
    isOpen: false,
    difficulty: 'red',
    type: 'slope',
  },
  {
    prefix: '33',
    name: "S'n",
    fullName: "33-S'n",
    isOpen: false,
    difficulty: 'black',
    type: 'slope',
  },
  {
    prefix: '34',
    name: 'Storekorken',
    fullName: '34-Storekorken',
    isOpen: false,
    difficulty: 'red',
    type: 'slope',
  },
  {
    prefix: '35',
    name: 'Bukkene Bruse',
    fullName: '35-Bukkene Bruse',
    isOpen: false,
    difficulty: 'blue',
    type: 'slope',
  },
  {
    prefix: '36',
    name: 'Anne',
    fullName: '36-Anne-løypa',
    isOpen: false,
    difficulty: 'blue',
    type: 'slope',
  },
  {
    prefix: '37',
    name: 'Hexeløypa',
    fullName: '37-Hexeløypa',
    isOpen: false,
    difficulty: 'red',
    type: 'slope',
  },
  {
    prefix: '41',
    name: 'Arne',
    fullName: '41-Arne-løypa',
    isOpen: false,
    difficulty: 'blue',
    type: 'slope',
  },
  {
    prefix: '42',
    name: 'Sentrumsløypa',
    fullName: '42-Sentrumsløypa',
    isOpen: false,
    difficulty: 'green',
    type: 'slope',
  },
  {
    prefix: '43',
    name: 'Barne',
    fullName: '43-Barne-løypa',
    isOpen: false,
    difficulty: 'green',
    type: 'slope',
  },
  {
    prefix: '44',
    name: 'Trineløypa',
    fullName: '44-Trineløypa',
    isOpen: false,
    difficulty: 'blue',
    type: 'slope',
  },
  {
    prefix: '45',
    name: 'Fjell',
    fullName: '45-Fjell-løypa',
    isOpen: false,
    difficulty: 'green',
    type: 'slope',
  },
  {
    prefix: '46',
    name: 'Fjellrypa',
    fullName: '46-Fjellrypa',
    isOpen: false,
    difficulty: 'green',
    type: 'slope',
  },
  {
    prefix: '47',
    name: 'Havsdalsløypa',
    fullName: '47-Havsdalsløypa',
    isOpen: false,
    difficulty: 'blue',
    type: 'slope',
  },
  {
    prefix: '48',
    name: 'Fjellcrossen',
    fullName: '48-Fjellcrossen',
    isOpen: false,
    difficulty: 'blue',
    type: 'slope',
  },
  {
    prefix: 'A',
    name: 'Halstensgårdheisen',
    fullName: 'A-Halstensgårdheisen',
    isOpen: false,
    type: 'lift',
  },
  {
    prefix: 'B',
    name: 'Fugleleiken',
    fullName: 'B-Fugleleiken',
    isOpen: false,
    type: 'lift',
  },
  {
    prefix: 'D',
    name: 'Geiloheisen ekspress',
    fullName: 'D-Geiloheisen ekspress',
    isOpen: false,
    type: 'lift',
  },
  {
    prefix: 'G',
    name: 'Slaattaheisen',
    fullName: 'G-Slaattaheisen',
    isOpen: false,
    type: 'lift',
  },
  {
    prefix: 'G',
    name: 'Barneheisen',
    fullName: 'G-Barneheisen',
    isOpen: false,
    type: 'lift',
  },
  {
    prefix: 'G',
    name: 'Slaatta skibånd',
    fullName: 'G-Slaatta skibånd',
    isOpen: false,
    type: 'lift',
  },
  {
    prefix: 'H',
    name: 'Korken',
    fullName: 'H-Korken',
    isOpen: false,
    type: 'lift',
  },
  {
    prefix: 'K',
    name: 'Arnetrekket',
    fullName: 'K-Arnetrekket',
    isOpen: false,
    type: 'lift',
  },
  {
    prefix: 'K',
    name: 'Barnetrekket',
    fullName: 'K-Barnetrekket',
    isOpen: false,
    type: 'lift',
  },
  {
    prefix: 'K',
    name: 'Havsdalen skibånd 1',
    fullName: 'K-Havsdalen skibånd 1',
    isOpen: false,
    type: 'lift',
  },
  {
    prefix: 'L',
    name: 'Fjellheisen',
    fullName: 'L-Fjellheisen',
    isOpen: false,
    type: 'lift',
  },
]

export const mapItemsRawVestlia = [
  {
    prefix: '50',
    name: 'Bjødnastigen',
    fullName: '50-Bjødnastigen',
    isOpen: false,
    difficulty: 'green',
    type: 'slope',
  },
  {
    prefix: '51',
    name: 'Bjødnaløypa',
    fullName: '51-Bjødnaløypa',
    isOpen: false,
    difficulty: 'green',
    type: 'slope',
  },
  {
    prefix: '52',
    name: 'Eivaløypa',
    fullName: '52-Eivaløypa',
    isOpen: false,
    difficulty: 'blue',
    type: 'slope',
  },
  {
    prefix: '53',
    name: 'Vestlialøypa',
    fullName: '53-Vestlialøypa',
    isOpen: false,
    difficulty: 'red',
    type: 'slope',
  },
  {
    prefix: '54',
    name: 'Randi',
    fullName: '54-Randi-løypa',
    isOpen: false,
    difficulty: 'red',
    type: 'slope',
  },
  {
    prefix: '55',
    name: 'Geiloparken',
    fullName: '55-Geiloparken',
    isOpen: false,
    difficulty: 'black',
    type: 'slope',
  },
  {
    prefix: '56',
    name: 'Trollklubben',
    fullName: '56-Trollklubben',
    isOpen: false,
    difficulty: 'green',
    type: 'slope',
  },
  {
    prefix: '57',
    name: 'Trollbakken m/park',
    fullName: '57-Trollbakken m/park',
    isOpen: false,
    difficulty: 'green',
    type: 'slope',
  },
  {
    prefix: '58',
    name: 'Hallingen',
    fullName: '58-Hallingen',
    isOpen: false,
    difficulty: 'red',
    type: 'slope',
  },
  {
    prefix: '59',
    name: 'Asle',
    fullName: '59-Asle-løypa',
    isOpen: false,
    difficulty: 'red',
    type: 'slope',
  },
  {
    prefix: '61',
    name: 'Hufseløypa',
    fullName: '61-Hufseløypa',
    isOpen: false,
    difficulty: 'green',
    type: 'slope',
  },
  {
    prefix: '63',
    name: 'Davidløypa',
    fullName: '63-Davidløypa',
    isOpen: false,
    difficulty: 'blue',
    type: 'slope',
  },
  {
    prefix: '64',
    name: 'Guroløypa',
    fullName: '64-Guroløypa',
    isOpen: false,
    difficulty: 'blue',
    type: 'slope',
  },
  {
    prefix: '65',
    name: 'Toneløypa',
    fullName: '65-Toneløypa',
    isOpen: false,
    difficulty: 'blue',
    type: 'slope',
  },
  {
    prefix: '66',
    name: 'Eventyrløypa',
    fullName: '66-Eventyrløypa',
    isOpen: false,
    difficulty: 'red',
    type: 'slope',
  },
  {
    prefix: '68',
    name: 'Kikutløypa',
    fullName: '68-Kikutløypa',
    isOpen: false,
    difficulty: 'green',
    type: 'slope',
  },
  {
    prefix: 'M',
    name: 'Vestliaheisen ekspress',
    fullName: 'M-Vestliaheisen ekspress',
    isOpen: false,
    type: 'lift',
  },
  {
    prefix: 'M',
    name: 'Bjødnaheisen',
    fullName: 'M-Bjødnaheisen',
    isOpen: false,
    type: 'lift',
  },
  {
    prefix: 'M',
    name: 'Trollheisen',
    fullName: 'M-Trollheisen',
    isOpen: false,
    type: 'lift',
  },
  {
    prefix: 'N',
    name: 'Trollklubben',
    fullName: 'N-Trollklubben',
    isOpen: false,
    type: 'lift',
  },
  {
    prefix: 'N',
    name: 'Trollklubben skibånd',
    fullName: 'N-Trollklubben skibånd',
    isOpen: false,
    type: 'lift',
  },
  {
    prefix: 'P',
    name: 'Hufseheisen',
    fullName: 'P-Hufseheisen',
    isOpen: false,
    type: 'lift',
  },
  {
    prefix: 'P',
    name: 'Kikut skibånd',
    fullName: 'P-Kikut skibånd',
    isOpen: false,
    type: 'lift',
  },
  {
    prefix: 'R',
    name: 'Toppheisen',
    fullName: 'R-Toppheisen',
    isOpen: false,
    type: 'lift',
  },
  {
    prefix: 'S',
    name: 'Kikutheisen ekspress',
    fullName: 'S-Kikutheisen ekspress',
    isOpen: false,
    type: 'lift',
  },
]

export const mapSides: MapSide[] = [
  {
    name: 'Slaatta, Havsdalen, Geiloheisen + Halstensgard',
    image: '/src/images/SlaattaHavsdalenGeiloheisen+Halstensgard.png',
    mapItems: mapItemsRawSlatta as MapItem[],
    coordinates: slattaCoordinates
  },
  {
    name: 'Kikut + Vestlia',
    image: '/src/images/Kitkut+Vestlia.png',
    mapItems: mapItemsRawVestlia as MapItem[],
    coordinates: vestliaCoordinates
  }
];
